[package]
name = "q_less_one_word"
version = "0.1.0"
edition = "2021"

[dependencies]
multimap = "0.8.3"
num = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


